---
version: "3.8"
services:
  test:
    network_mode: "host"
    container_name: "test"
    hostname: "test"
    build:
      context: "."
      target: "test"
    volumes:
      - "./:/usr/src/app"
  clab:
    image: "ghcr.io/srl-labs/clab"
    network_mode: "host"
    working_dir: "/src"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/run/netns:/var/run/netns"
      - "/etc/hosts:/etc/hosts"
      - "./:/src"
      - "./clab-topo-netconf.yml:/src/clab-topo-netconf.yml"
    pid: "host"
    command: "containerlab deploy -t clab-topo-netconf.yml"
    # If you want to destroy the lab, ovveride the command while executing
    # docker-compose service
    # docker-compose run clab containerlab destroy -t clab-topo-netconf.yml
    privileged: true
    tty: true
  cli:
    build:
      target: "cli"
      context: "."
    network_mode: "host"
    volumes:
      - "./:/usr/src/app"
    image: "${COMMIT_IMAGE:-h4ndzdatm0ld/norconf:latest}"
