## Nornir Groups File 
---
CSR: 
  username: 'cisco'
  password: 'cisco'
  platform: ios
  port: 22

NOKIA:
  username: 'admin'
  password: 'admin'
  platform: alcatel_sros
  port: 22
  data:
    target: candidate
  connection_options:
    netconf:
      port: 830
      username: netconf
      password: NCadmin123
      extras:
        allow_agent: false
        hostkey_verify: false
        look_for_keys: false

IOSXR:
  username: htinoco
  password: admin
  platform: iosxr
  port: 22
  connection_options:
    netconf:
      port: 830
      username: htinoco
      password: admin
      extras:
        allow_agent: false
        hostkey_verify: false
        look_for_keys: false
  data:
    target: candidate
  
IOS:
  username: cisco
  password: cisco
  platform: ios
  port: 22
  